[package]
name = "rustxes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustxes"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rayon = "1.7.0"
chrono = {version = "0.4.29" }
uuid = {version = "1.4.1", features = ["v4"]}
quick-xml = "0.30.0"
flate2 = "1.0"
polars = {version = "0.32.1", features = ["dtype-slim"]}
pyo3-polars = "0.6.0"