[package]
name = "rustxes"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustxes"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
rayon = "1.7.0"
quick-xml = "0.30.0"
flate2 = "1.0"
polars = {version = "0.38.1", features = ["dtype-slim","lazy","timezones","rows","diagonal_concat"]}
pyo3-polars = "0.12.0"
serde_json = "1.0.105"
serde = {version = "1.0.188", features = ["derive"]}
chrono = {version = "0.4.29", features = ["serde"] }
uuid = {version = "1.4.1", features = ["v4", "serde"]}
process_mining = "0.2.5"
# process_mining = {path = "../../rust-bridge-process-mining/process_mining"}
